### ISSUE TITLE
[Bug] Theme reverts to the default one after some time

### ISSUE THREAD

**Issue by Patrxgt** [SteamClientHomebrew/Millennium#65] opened 2024-07-17 13:26 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

After using Steam for an hour or so theming starts to slowly return to default one. First the small window that shows up when starting a game, then parts of the overlay when the game is running, then the store page and at the end the whole library and the top bar. It happens in the online mode, but is more frequent in the offline mode or when PC doesn't have any connection to the internet.

### Expected Behavior

Theme should not change overtime.

### Steps To Reproduce

1. Turn on Steam and apply any theme.
2. Restart Steam (preferably in the offline mode or turn off any connection to the internet in the network card settings).
3. Wait for an hour or two.
4. Try turning on the game.

### Operating System

Windows

### Anything else?

It's not really connected in any way to this issue, but the small notification that shows up when starting a game with the Steam Overlay turned on isn't themed properly and shows up as an empty rectangle in the main color of the applied theme.

**Comment by ShadowMonster99** [comment] 2024-07-19 18:00
Try installing the [beta version of Millennium](https://docs.steambrew.app/users/installing).

**Comment by Patrxgt** [comment] 2024-07-19 21:49
Looks like it still happens without internet connection/in offline mode. Also, now settings for a theme got reset and I can't find any button to configure an active theme.

**Comment by ShadowMonster99** [comment] 2024-07-20 18:49
So your main issue is theming in offline mode?

**Comment by Patrxgt** [comment] 2024-07-20 21:23
After installing the beta version, yes.

**Comment by ShadowMonster99** [comment] 2024-07-21 00:36
Okay perfect, i’ll have a look. I’ll close this issue once the issue is fixed!

**Comment by shdwmtr** [comment] 2024-10-12 15:58
This should have been fixed several updates ago, just forgot to close this!

**Closed by shdwmtr** 2024-10-12 15:58 UTC
Labels: bug
