### ISSUE TITLE
[Bug]Steam on "Steam Families Beta" can't use Millennium

### ISSUE THREAD

**Issue by aipiao-gh** [SteamClientHomebrew/Millennium#76] opened 2024-08-09 01:50 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

![image](https://github.com/user-attachments/assets/b7161655-7f19-40ac-b76c-500176533ee6)
Steam Testing:  Steam Families Beta
Steam Version:  1722380543
Steam API Version:  SteamClient021
Millennium Version: 2.9.4

### Expected Behavior

Open Steam and it can work

### Steps To Reproduce

1.install Millennium
2.can't start Steam

### Operating System

Windows

**Comment by yufengOvO** [comment] 2024-08-09 03:36
I also encountered this bug, steam will crash

**Comment by ShadowMonster99** [comment] 2024-08-09 03:42
This could possibly be caused by your antivirus. Ill take a look regardless.

**Comment by ShadowMonster99** [comment] 2024-08-09 03:55
I seem to have located the issues. I should be fixed soon

**Comment by ShadowMonster99** [comment] 2024-08-13 17:20
Just an update on this, It turns out this is still an issue (but I now know what the issue is). Its because another app is running on port 8080, which is required to be open for millennium. [Learn more...](https://docs.steambrew.app/users/trouble-shooting#issues-with-another-app-running-on-port-8080)

**Comment by shdwmtr** [comment] 2024-08-28 02:09
Fixed in 2.10.0

**Closed by shdwmtr** 2024-08-28 02:09 UTC
Labels: bug
