### ISSUE TITLE
[Bug] UI becomes unresponsive during network fluctuations

### ISSUE THREAD

**Issue by pasical** [SteamClientHomebrew/Millennium#113] opened 2024-09-23 12:17 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

After a period of time (which can be a split second) when the network is disconnected and comes back up, the steam UI becomes unusable, loaded pages can continue to be viewed, but none of the other controls work.

### Expected Behavior

All buttons are not clickable and have no selection effect. The scrollbar works but the UI gets stuck. At this point you can only force stop all processes of steam and restart.

### Steps To Reproduce

Create some network volatility, like
- Unplug the cable and plug it in right away.
- Open and then close the proxy server.
- Turning on the computer after hibernation.
- Rapidly switch between Ethernet and Wi-Fi.

### Operating System

Windows

**Comment by shdwmtr** [comment] 2024-09-27 01:00
I'm unable to reproduce the issue with rapidly switching from Ethernet to Wi-Fi, however I can reproduce the issue on hibernation. I'll look further into it!

**Comment by pasical** [comment] 2024-10-11 03:58
This screenshot is the output of the console when I triggered the bug
![image](https://github.com/user-attachments/assets/c3bcba1c-79b0-4e0c-96bb-ddd1659aca8a)

**Comment by shdwmtr** [comment] 2024-10-12 16:01
What method did you use to trigger it?

**Comment by pasical** [comment] 2024-10-12 16:08
> What method did you use to trigger it?

I turned the proxy server off and on, this should be the fastest way to reproduce

**Comment by shdwmtr** [comment] 2024-10-12 16:12
I dont use a proxy server, so I have no way of reproducing like that

**Comment by pasical** [comment] 2024-10-12 16:12
> What method did you use to trigger it?

It may be that I used the virtual NIC mode, also called tun mode, so it's roughly equivalent to pulling out the network card and plugging it in again

**Comment by adrienrichmond** [comment] 2024-10-18 03:02
Same problem.

**Comment by shdwmtr** [comment] 2024-10-18 21:17
I believe I've fixed it, it will be in the next update.

**Comment by shdwmtr** [comment] 2024-10-28 14:52
After some further bug testing I'm relatively confident this is fixed. Expect the release soon! I'm going to close this issue, but if you have further problems open it back up.

**Closed by shdwmtr** 2024-10-28 14:52 UTC
Labels: bug
